/**
 * Message counter for existing Obsidian notes
 *
 * Counts and extracts messages from note body across all 3 formats
 * generated by formatMessage() in markdown.ts.
 */

import { ALL_PLATFORM_LABELS } from './constants';
import { nextFenceState, type OpenFence } from './code-fence';

/**
 * Build label alternation from ALL_PLATFORM_LABELS: "User|Gemini Notebook|...".
 *
 * Uses ALL_PLATFORM_LABELS (current + superseded names) because this module
 * reads notes written by *earlier* versions. Missing a retired label would
 * make countExistingMessages() return 0 and append-mode duplicate the whole
 * conversation (ADR-023).
 */
const LABEL_ALTERNATION = ['User', ...ALL_PLATFORM_LABELS, 'Assistant'].join('|');

/**
 * Pattern matching a message start in any of the 3 formats `formatMessage()`
 * emits: the callout header `> [!TYPE] Label`, or the blockquote/plain heading
 * `**Label:**`.
 *
 * Deliberately one pattern rather than one per format. A saved note is NOT
 * guaranteed to be homogeneous: the Obsidian save path runs
 * `flattenLargeCallouts()`, which rewrites oversized callouts into the
 * `**Label:**` form and leaves shorter ones alone. Counting only the form that
 * happened to match first undercounts such a note, and append mode then
 * re-appends the difference verbatim (issue #406, ADR-028).
 */
const MESSAGE_START_PATTERN = new RegExp(
  `^(?:> \\[!\\w+\\] (?:${LABEL_ALTERNATION})\\b|\\*\\*(?:${LABEL_ALTERNATION}):\\*\\*)`
);

/**
 * Line indices at which a message starts, ignoring anything inside a fenced
 * code block.
 *
 * The single source of truth for "where are the messages" — both
 * {@link countExistingMessages} and {@link extractTailMessages} read it, so
 * the count and the offset it is used at cannot drift apart.
 */
interface BodyScan {
  /** Line indices at which a message starts. */
  readonly starts: readonly number[];
  /** Fence still open when the body ran out, or null. */
  readonly openFence: OpenFence;
}

function scanBody(lines: readonly string[]): BodyScan {
  const starts: number[] = [];
  let fence: OpenFence = null;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Only column-0 backtick fences are tracked, for two separate reasons:
    //
    // - Blockquote markers are NOT stripped: inside a callout every line
    //   carries a `> ` prefix, and a nested `> > [!TYPE] Label` cannot match a
    //   start anyway (ADR-028).
    // - Tildes are NOT recognised: the writer only ever emits backtick fences,
    //   so a column-0 `~~~` in a note is prose. Honouring it would open a block
    //   that hides every message after it — silently stalling append mode
    //   (ADR-029).
    //
    // The tracker itself is length- and character-aware, so a fence nested
    // inside a longer one is content rather than a delimiter (issue #433).
    const step = nextFenceState(fence, line, { openChars: ['`'] });
    fence = step.state;
    if (step.isDelimiter || fence !== null) continue;

    if (MESSAGE_START_PATTERN.test(line)) starts.push(i);
  }

  return { starts, openFence: fence };
}

/** Line indices at which a message starts. */
function scanMessageStarts(lines: readonly string[]): readonly number[] {
  return scanBody(lines).starts;
}

/**
 * The fence still open when `body` ended, or null when every fence is closed.
 *
 * A body that ends inside a code block is the shape where the count can be
 * wrong with no other symptom: an overcount makes `buildAppendContent()`
 * return null, and the caller then reports a perfectly successful no-op
 * (ADR-029).
 */
export function unterminatedFence(body: string): OpenFence {
  return scanBody(body.split('\n')).openFence;
}

/**
 * Count conversation messages in a note body.
 * Supports all 3 message formats generated by formatMessage(), including a
 * note that mixes them after callout flattening (issue #406).
 */
export function countExistingMessages(body: string): number {
  return scanMessageStarts(body.split('\n')).length;
}

/**
 * Extract messages after skipCount from a formatted note body.
 * Returns formatted markdown for only the tail (new) messages.
 *
 * When the matched message is preceded by a freshly generated `## ` question
 * header (issue #187), the lookback also captures that header so append-mode
 * output keeps the TOC entry intact.
 */
export function extractTailMessages(fullBody: string, skipCount: number): string {
  if (skipCount <= 0) return fullBody;

  const lines = fullBody.split('\n');
  const starts = scanMessageStarts(lines);
  if (skipCount >= starts.length) return '';

  let tailStartLine = starts[skipCount];
  // Look back across blank lines for an immediately preceding `## ` header
  // (issue #187). fullBody is freshly generated so the only `## ` lines
  // are auto-generated question headers.
  let lookback = tailStartLine - 1;
  while (lookback >= 0 && lines[lookback].trim() === '') lookback--;
  if (lookback >= 0 && /^## /.test(lines[lookback])) {
    tailStartLine = lookback;
  }

  return lines.slice(tailStartLine).join('\n');
}
